<?php 
    $product = $block->getCurrentProduct();
    $model = $block->getAfraModel();
    $app_data=$model->getCollection()->getFirstItem();
    $token = substr(md5(microtime()),rand(0,26),5);
    $questiondata=$block->getAskQuestion($product,$app_data,$token);
?>
<?php if(!empty($app_data->getData())): ?>
<?php 
       	
       	if ($questiondata !='Not Authorized') {
       	$questions = json_decode($questiondata);
       	
       	if ($questions != null) {
       	?>
        <div id="aframark-container-micro" >
       		<img src="<?php echo $this->getViewFileUrl("Axtrics_Aframark::images/aframark-icon.svg"); ?>" width="16"><a id="question-tab" href="#tab-label-questionstab"><?php echo $questions->totalRecords.' answered questions';?></a>
        </div>
       	<?php
       	}	
       	else
       	{
		    ?>
        <div id="aframark-container-micro" >
       	<img src="<?php echo $this->getViewFileUrl("Axtrics_Aframark::images/aframark-icon.svg"); ?>" width="16"><a id="question-tab" href="#tab-label-questionstab">Ask a question</a>
       </div> 
 		   <?php     	
 		     }
       	}

?>
<?php endif; ?>
<script type="text/javascript">
        require([
        'jquery'
    ], function ($) {
        'use strict';
       
            $("#question-tab").on("click" ,function(e) {
           	e.preventDefault();
             $('html, body').animate({
                scrollTop: $("#tab-label-questionstab").offset().top
              }, 1000);
                $("#tab-label-questionstab").trigger( "click" );
            });
});
</script>
