<?php 
    $product = $block->getCurrentProduct();
    $model = $block->getAfraModel();
    $app_data=$model->getCollection()->getFirstItem();
    $token = substr(md5(microtime()),rand(0,26),5);
    $url= $block->AframarkUrl();
    $widget= $block->getWiget();
    $widgetips= $block->getwidgetips();
    $widgetips=explode(",",$widgetips);
    $matched=false;
    //Ip Find

        if (in_array($model->getUserip(), $widgetips)){

        $matched= true;
    }
    
  
?>
<?php if(!empty($app_data->getData())): ?>
<script type="text/javascript" async="" src="<?php echo $url;?>/js/Widgets/WidgetQA.js?ver=0.2.9"></script>
<div id="aframark-container" data-ak-api-token='<?php echo $token.$app_data['store_token'] ?>' data-ak-merchant-code='<?php echo $app_data['merchant_code'] ?>' data-ak-sku='<?php echo $product->getSku(); ?>'></div>
<?php endif; ?>

<script type="text/javascript">
        require([
        'jquery'
    ], function ($) {
        'use strict';
       
        $(document).ready(function(){
            var widget="<?php echo $block->getWiget();?>";
            var matched="<?php echo $matched;?>";
            
            if(widget==false){
                
                if(matched==false){
                  
                   $('ul li').each(function(index,value) {
                    if($(this).find('a').attr('href')=='#questionstab'){
                        $(this).hide();
                    }
                   //console.log("shintuuu",index,value.find('href'));
                });
                $("#questionstab").hide();
            
                }
                
            }
        });
});
</script>